### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by elect86** [nvpro-samples/gl_commandlist_basic#2] opened 2016-04-26 11:06 UTC
So, I followed all your instructions:
- cloned gl_commandlist_basic, shared_external, shared_sources and build_all at the same level (same directory)
- `cmake -G "Visual Studio 14 2015 Win64"` inside build_all
- opened `ALL_BUILD.vcxproj` with vs2015 CE and built

Complete output:

https://gist.github.com/elect86/a5272f2350e746d22f0352553d55669d

most of errors look like:

> error C2039: 'int_least8_t': is not a member of '`global namespace''
> error C2873: 'int_least8_t': symbol cannot be used in a using-declaration

**Comment by pixeljetstream** [comment] 2019-11-14 14:06
closing as codebase has changed a lot and couldn't reproduce this, we recommend visual studio 2017 on windows by time or writing this.

**Closed as completed by pixeljetstream** 2019-11-14 14:06 UTC
